using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataIntegration.Stores
{
    public class QueryStrings
    {
        public string DAYINFO = @"SELECT TRANSDATE , TIMESTART, TIMEEND , TRANSEND, WEATHER ,  WHOOPEN , WHOCLOSE , WHOOPENNAME , 
                                 WHOCLOSENAME, TEMPERATURE, EMPWAGES ,  NUMSHIFTS ,STORENUM ,SALESNET ,TAX1     , SALESGROSS, 
                                NUMTRANS , NUMCOUPONS, COUPONVALUE,  NUMVOIDS, VOIDVALUE, NUMCLIENTS, CLIENTSALES, POINTSAWARDED,
                                SUMGROUP1, SUMGROUP2, SUMGROUP3, SUMGROUP4, SUMGROUP5, SUMGROUP6,  SUMGROUP7,  SUMGROUP8,  
                                SUMGROUP9,  SUMGROUP10, REEXPORT, OPENDATE, SNUM, UID
                                FROM dba.DAYINFO where SNUM is not null AND TIMEEND IS NOT NULL";

        public string POSDETAIL = @"SELECT UNIQUEID, TRANSACT, PRODNUM, WHOORDER, WHOAUTH, COSTEACH, QUAN,
                                TIMEORD, PRINTLOC, SEATNUM, MINUTES, NOTAX, HOWORDERED, STATUS,
                                NEXTPOS, PRIORPOS, RECPOS, PRODTYPE, APPLYTAX1, APPLYTAX2, APPLYTAX3, APPLYTAX4,
                                APPLYTAX5, REDUCEINVENTORY, STORENUM, STATNUM, RECIPECOSTEACH, OPENDATE, MEALTIME,
                                LINEDES, REVCENTER, QUESTIONID, ORIGCOSTEACH, NETCOSTEACH, DISCOUNT,
                                GRATEXEMPT, AUTHCODE, SNUM, SPLITPRODNUM, REPGROUP, LASTUPDATE, LASTSTORE, HOEXCHANGERATE, MASTERITEM, ISTESTDATA
                                FROM DBA.POSDETAIL WHERE UNIQUEID IS NOT NULL";
    }
}
