using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataIntegration.Stores
{
    public class QueryStrings
    {
        public string DAYINFO = @"SELECT TRANSDATE , TIMESTART, TIMEEND , TRANSEND, WEATHER ,  WHOOPEN , WHOCLOSE , WHOOPENNAME , 
                                 WHOCLOSENAME, TEMPERATURE, EMPWAGES ,  NUMSHIFTS ,STORENUM ,SALESNET ,TAX1     , SALESGROSS, 
                                NUMTRANS , NUMCOUPONS, COUPONVALUE,  NUMVOIDS, VOIDVALUE, NUMCLIENTS, CLIENTSALES, POINTSAWARDED,
                                SUMGROUP1, SUMGROUP2, SUMGROUP3, SUMGROUP4, SUMGROUP5, SUMGROUP6,  SUMGROUP7,  SUMGROUP8,  
                                SUMGROUP9,  SUMGROUP10, REEXPORT, OPENDATE, SNUM, UID
                                FROM dba.DAYINFO where SNUM is not null AND TIMEEND IS NOT NULL";

        public string POSDETAIL = @"SELECT UNIQUEID, TRANSACT, PRODNUM, WHOORDER, WHOAUTH, COSTEACH, QUAN,
                                TIMEORD, PRINTLOC, SEATNUM, MINUTES, NOTAX, HOWORDERED, STATUS,
                                NEXTPOS, PRIORPOS, RECPOS, PRODTYPE, APPLYTAX1, APPLYTAX2, APPLYTAX3, APPLYTAX4,
                                APPLYTAX5, REDUCEINVENTORY, STORENUM, STATNUM, RECIPECOSTEACH, OPENDATE, MEALTIME,
                                LINEDES, REVCENTER, QUESTIONID, ORIGCOSTEACH, NETCOSTEACH, DISCOUNT,
                                GRATEXEMPT, AUTHCODE, SNUM, SPLITPRODNUM, MASTERITEM
                                FROM DBA.POSDETAIL WHERE UNIQUEID IS NOT NULL";
        public string POSHEADER = @"SELECT TRANSACT, TABLENUM, TIMESTART, TIMEEND, NUMCUST, TAX1, TAX2, TAX3, TAX4, TAX5,
                                TAX1ABLE, TAX2ABLE, TAX3ABLE, TAX4ABLE, TAX5ABLE, NETTOTAL, WHOSTART, WHOCLOSE, ISSPLIT,
                                SALETYPEINDEX, EXP, WAITINGAUTH, STATNUM, STATUS, FINALTOTAL, STORENUM, PUNCHINDEX, GRATUITY, OPENDATE, MEMCODE,
                                TOTALPOINTS, POINTSAPPLIED, UPDATESTATUS, ISDELIVERY, SCHEDULEDATE, TAX1EXEMPT, TAX2EXEMPT, TAX3EXEMPT, TAX4EXEMPT, TAX5EXEMPT,
                                MEMRATE, MEALTIME, ISINTERNET, REVCENTER, PUNCHIDXSTART, STATNUMSTART, SECNUM, GRATAMOUNT, SHIPTO, ENFORCEDGRAT, NUMPRINTEDFINAL,
                                REFID, RSTORDNUM, EMAILADDRID, LABEL, SNUM
                                FROM DBA.POSHEADER 
                                WHERE TRANSACT IS NOT NULL AND STATUS = 3";
        public string POSBANK = @"SELECT UNIQUEID, PUNCHINDEX, METHODNUM, CALCTENDERED,
                                  EXCHANGERATE, DATEENTERED, ENTRYTYPE, REFCODE,
                                  OPENDATE, WHOAUTH, PLINK, REASONID, SAFENUM, FLOATNUM, DENOMNUM,
                                  WASPROCESSED, ISACTIVE, STATNUM, MEMCODE, QLINK, UPDATESTATUS, SNUM
                                  FROM DBA.POSBANK WHERE UNIQUEID IS NOT NULL";
        public string PUNCHPAYROLL = @"SELECT PUNCHINDEX, PUNCHIN, PUNCHOUT, PAYRATE, ORIGPAYRATE, JOBTYPE, EMPNUM, 
                                    OPENDATE, SHIFTINDEX, TIP, QUANVOID, VOIDSALES, OTHOURS, OTWAGE, SHIFTCOUNT, 
                                    BREAKCOUNT, MEALTAKEN, BREAKTAKEN, BREAKSCANCELLED , BREAKWAIVED, MEALWAIVED, 
                                    TOTALHOURS, BREAKUNPAIDHOURS,  BREAKPAIDHOURS,  BREAKHOURS, PAIDHOURS,
                                    REGHOURS,  REGRATE, TOTALWAGE, AVERAGEDPAYRATE, REVCENTER, NUMNOSALE, TILLBALANCE 
                                    FROM DBA.PUNCHPAYROLL WHERE PUNCHINDEX IS NOT NULL";
        public string STOCKTAKEDETAIL = @"SELECT UNIQUEID, STOCKTAKENUM, INVENNUM, STARTINV, ENDINV, ROUND(POSUSED,2) AS POSUSED,
                                        SPILL, TRANSFERIN, TRANSFEROUT, OTHER, STARTDATE, ENDDATE, WHOENTER,
                                        ROUND(PURCHASED,2) AS PURCHASED, BATCHUSED, ROUND(OVERSHORT,2) AS OVERSHORT, ROUND(SHORTVALUE,2) AS SHORTVALUE,
                                        WAREHOUSENUM, REASON, SNUM,
                                        PLINK, STORETRANSFEROUT, QTYINTRANSFER, QLINK
                                        FROM DBA.STOCKTAKEDETAIL WHERE UNIQUEID IS NOT NULL";
        public string EMPLOYEE = @"SELECT EMPNUM, EMPNAME, EMPLASTNAME, DATEENTERED,
                                   ADRESS1, ADRESS2, STARTWORK, ENDWORK, ISACTIVE, POSNAME,
                                   HOURLYWAGE, GENDER, SIN, SNUM
                                   FROM DBA.EMPLOYEE";

    }
}
